spring:
  dataSource:
    mysql:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring
      username: root
      password: ri1yvi2txgt6
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp